// TODO: Add more enumerations from the wiki
namespace SabreTools.Serialization.Models.PlayStation3
{
    /// <see href="https://psdevwiki.com/ps3/PARAM.SFO"/> 
    public enum DataFormat : ushort
    {
        /// <summary>
        /// UTF-8 Special Mode, NOT NULL terminated
        /// </summary>
        /// <remarks>
        /// Used in SFO's generated by the system and/or linked to an user (Game Saves and Trophies).
        /// </remarks>
        UTF8SpecialMode = 0x0004,

        /// <summary>
        /// UTF-8 character string, NULL terminated (0x00)
        /// </summary>
        /// <remarks>
        /// Can be used any character from the system fonts. The NULL byte is counted as part of the used bytes in len
        /// </remarks>
        UTF8 = 0x0204,

        /// <summary>
        /// Integer 32 bits unsigned
        /// </summary>
        /// <remarks>
        /// Always has a length of 4 bytes in len and max_len (even in the case some bytes are not used, all them are marked as used)
        /// </remarks>
        Integer = 0x0404,
    }
}