//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
//This source code was auto-generated by MonoXSD
//

// Originally sourced from https://github.com/aaru-dps/Aaru/blob/v5.4/CICMMetadata/dotnet/cicm.cs
// The above header is from the original generated code
// Some formatting cleanup has been done to fit project standards

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace SabreTools.Data.Models.CICM
{
    [GeneratedCode("xsd", "0.0.0.0")]
    [Serializable]
    [DesignerCategory("code")]
    public class Advertisement
    {
        public string Manufacturer { get; set; }

        public string Product { get; set; }

        public FileType File { get; set; }

        public ulong FileSize { get; set; }

        public ulong Frames { get; set; }

        [XmlIgnore]
        public bool FramesSpecified { get; set; }

        public double Duration { get; set; }

        public float MeanFrameRate { get; set; }

        [XmlIgnore]
        public bool MeanFrameRateSpecified { get; set; }

        [XmlArrayItem("Checksum", IsNullable = false)]
        public Checksum[] Checksums { get; set; }

        [XmlElement("AudioTrack")]
        public AudioTracks[] AudioTrack { get; set; }

        [XmlElement("VideoTrack")]
        public VideoTracks[] VideoTrack { get; set; }

        [XmlElement("SubtitleTrack")]
        public SubtitleTracks[] SubtitleTrack { get; set; }

        public Recording Recording { get; set; }
    }
}
