//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
//This source code was auto-generated by MonoXSD
//

// Originally sourced from https://github.com/aaru-dps/Aaru/blob/v5.4/CICMMetadata/dotnet/cicm.cs
// The above header is from the original generated code
// Some formatting cleanup has been done to fit project standards

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace SabreTools.Data.Models.CICM
{
    [GeneratedCode("xsd", "0.0.0.0")]
    [Serializable]
    [DesignerCategory("code")]
    public class DumpHardware
    {
        public string Manufacturer { get; set; }

        public string Model { get; set; }

        public string Revision { get; set; }

        public string Firmware { get; set; }

        public string Serial { get; set; }

        [XmlArrayItem("Extent", IsNullable = false)]
        public Extent[] Extents { get; set; }

        public Software Software { get; set; }
    }
}
