//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
//This source code was auto-generated by MonoXSD
//

// Originally sourced from https://github.com/aaru-dps/Aaru/blob/v5.4/CICMMetadata/dotnet/cicm.cs
// The above header is from the original generated code
// Some formatting cleanup has been done to fit project standards

using System;
using System.CodeDom.Compiler;
using System.Xml.Serialization;

namespace SabreTools.Data.Models.CICM
{
    [GeneratedCode("xsd", "0.0.0.0")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum Architecture
    {
        [XmlEnum("4004")]
        Item4004,

        [XmlEnum("4040")]
        Item4040,

        [XmlEnum("6502")]
        Item6502,

        [XmlEnum("65816")]
        Item65816,

        [XmlEnum("8008")]
        Item8008,

        [XmlEnum("8051")]
        Item8051,

        [XmlEnum("8080")]
        Item8080,

        [XmlEnum("8085")]
        Item8085,

        aarch64,

        am29000,

        amd64,

        apx432,

        arm,

        avr,

        avr32,

        axp,

        clipper,

        cray,

        esa390,

        hobbit,

        i86,

        i860,

        i960,

        ia32,

        ia64,

        m56k,

        m6800,

        m6801,

        m6805,

        m6809,

        m68k,

        m88k,

        mcs41,

        mcs48,

        mips32,

        mips64,

        msp430,

        nios2,

        openrisc,

        parisc,

        pdp1,

        pdp10,

        pdp11,

        pdp7,

        pdp8,

        pic,

        power,

        ppc,

        ppc64,

        prism,

        renesasrx,

        riscv,

        s360,

        s370,

        sh,

        sh1,

        sh2,

        sh3,

        sh4,

        sh5,

        sh64,

        sparc,

        sparc64,

        transputer,

        vax,

        we32000,

        x32,

        z80,

        z800,

        z8000,

        z80000,

        zarch,
    }

    [GeneratedCode("xsd", "0.0.0.0")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum BarcodeType
    {
        aztec,

        codabar,

        code11,

        code128,

        code39,

        code93,

        cpcbinary,

        ezcode,

        fim,

        itf,

        itf14,

        ean13,

        ean8,

        maxicode,

        isbn,

        isrc,

        msi,

        tof,

        shotcode,

        rm4scc,

        qr,

        ean5,

        ean2,

        [XmlEnum("qr")]
        qr1,

        postnet,

        postbar,

        plessey,

        pharmacode,

        pdf417,

        patchcode,
    }

    [GeneratedCode("xsd", "0.0.0.0")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum CaseScanElement
    {
        sleeve,

        inner,

        inlay,

        frontback,

        frontfull,

        boxfront,

        boxback,

        boxspine,

        external,
    }

    [GeneratedCode("xsd", "0.0.0.0")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum CaseType
    {
        jewel,

        bigjewel,

        slimjewel,

        sleeve,

        qpack,

        digisleeve,

        discboxslider,

        compacplus,

        keepcase,

        snapcase,

        softcase,

        ecopack,

        liftlock,

        spindle,

        ps2case,

        ps3case,

        bluraykeepcase,

        pscase,

        dccase,

        saturncase,

        xboxcase,

        xbox360case,

        xboxonecase,

        saturnbigcase,

        gccase,

        wiicase,

        unknown,
    }

    [GeneratedCode("xsd", "0.0.0.0")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum ChecksumType
    {
        fletcher16,

        fletcher32,

        adler32,

        crc16,

        crc16ccitt,

        crc32,

        crc64,

        md4,

        md5,

        dm6,

        ripemd128,

        ripemd160,

        ripemed320,

        sha1,

        sha224,

        sha256,

        sha384,

        sha512,

        sha3,

        skein,

        snefru,

        blake256,

        blake512,

        tiger,

        whirlpool,

        spamsum,
    }

    [GeneratedCode("xsd", "0.0.0.0")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum Language
    {
        aar,

        abk,

        ace,

        ach,

        ada,

        ady,

        afa,

        afh,

        afr,

        ain,

        aka,

        akk,

        alb,

        ale,

        alg,

        alt,

        amh,

        ang,

        anp,

        apa,

        ara,

        arc,

        arg,

        arm,

        arn,

        arp,

        art,

        arw,

        asm,

        ast,

        ath,

        aus,

        ava,

        ave,

        awa,

        aym,

        aze,

        bad,

        bai,

        bak,

        bal,

        bam,

        ban,

        baq,

        bas,

        bat,

        bej,

        bel,

        bem,

        ben,

        ber,

        bho,

        bih,

        bik,

        bin,

        bis,

        bla,

        bnt,

        bos,

        bra,

        bre,

        btk,

        bua,

        bug,

        bul,

        bur,

        byn,

        cad,

        cai,

        car,

        cat,

        cau,

        ceb,

        cel,

        cha,

        chb,

        che,

        chg,

        chi,

        chk,

        chm,

        chn,

        cho,

        chp,

        chr,

        chu,

        chv,

        chy,

        cmc,

        cop,

        cor,

        cos,

        cpe,

        cpf,

        cpp,

        cre,

        crh,

        crp,

        csb,

        cus,

        cze,

        dak,

        dan,

        dar,

        day,

        del,

        den,

        dgr,

        din,

        div,

        doi,

        dra,

        dsb,

        dua,

        dum,

        dut,

        dyu,

        dzo,

        efi,

        egy,

        eka,

        elx,

        eng,

        enm,

        epo,

        est,

        ewe,

        ewo,

        fan,

        fao,

        fat,

        fij,

        fil,

        fin,

        fiu,

        fon,

        fre,

        frm,

        fro,

        frr,

        frs,

        fry,

        ful,

        fur,

        gaa,

        gay,

        gba,

        gem,

        geo,

        ger,

        gez,

        gil,

        gla,

        gle,

        glg,

        glv,

        gmh,

        goh,

        gon,

        gor,

        got,

        grb,

        grc,

        gre,

        grn,

        gsw,

        guj,

        gwi,

        hai,

        hat,

        hau,

        haw,

        heb,

        her,

        hil,

        him,

        hin,

        hit,

        hmn,

        hmo,

        hrv,

        hsb,

        hun,

        hup,

        iba,

        ibo,

        ice,

        ido,

        iii,

        ijo,

        iku,

        ile,

        ilo,

        ina,

        inc,

        ind,

        ine,

        inh,

        ipk,

        ira,

        iro,

        ita,

        jav,

        jbo,

        jpn,

        jpr,

        jrb,

        kaa,

        kab,

        kac,

        kal,

        kam,

        kan,

        kar,

        kas,

        kau,

        kaw,

        kaz,

        kbd,

        kha,

        khi,

        khm,

        kho,

        kik,

        kin,

        kir,

        kmb,

        kok,

        kom,

        kon,

        kor,

        kos,

        kpe,

        krc,

        krl,

        kro,

        kru,

        kua,

        kum,

        kur,

        kut,

        lad,

        lah,

        lam,

        lao,

        lat,

        lav,

        lez,

        lim,

        lin,

        lit,

        lol,

        loz,

        ltz,

        lua,

        lub,

        lug,

        lui,

        lun,

        luo,

        lus,

        mac,

        mad,

        mag,

        mah,

        mai,

        mak,

        mal,

        man,

        mao,

        map,

        mar,

        mas,

        may,

        mdf,

        mdr,

        men,

        mga,

        mic,

        min,

        mis,

        mkh,

        mlg,

        mlt,

        mnc,

        mni,

        mno,

        moh,

        mon,

        mos,

        mul,

        mun,

        mus,

        mwl,

        mwr,

        myn,

        myv,

        nah,

        nai,

        nap,

        nau,

        nav,

        nbl,

        nde,

        ndo,

        nds,

        nep,

        @new,

        nia,

        nic,

        niu,

        nno,

        nob,

        nog,

        non,

        nor,

        nqo,

        nso,

        nub,

        nwc,

        nya,

        nym,

        nyn,

        nyo,

        nzi,

        oci,

        oji,

        ori,

        orm,

        osa,

        oss,

        ota,

        oto,

        paa,

        pag,

        pal,

        pam,

        pan,

        pap,

        pau,

        peo,

        per,

        phi,

        phn,

        pli,

        pol,

        pon,

        por,

        pra,

        pro,

        pus,

        [XmlEnum("qaa-qtz")]
        qaaqtz,

        que,

        raj,

        rap,

        rar,

        roa,

        roh,

        rom,

        rum,

        run,

        rup,

        rus,

        sad,

        sag,

        sah,

        sai,

        sal,

        sam,

        san,

        sas,

        sat,

        scn,

        sco,

        sel,

        sem,

        sga,

        sgn,

        shn,

        sid,

        sin,

        sio,

        sit,

        sla,

        slo,

        slv,

        sma,

        sme,

        smi,

        smj,

        smn,

        smo,

        sms,

        sna,

        snd,

        snk,

        sog,

        som,

        son,

        sot,

        spa,

        srd,

        srn,

        srp,

        srr,

        ssa,

        ssw,

        suk,

        sun,

        sus,

        sux,

        swa,

        swe,

        syc,

        syr,

        tah,

        tai,

        tam,

        tat,

        tel,

        tem,

        ter,

        tet,

        tgk,

        tgl,

        tha,

        tib,

        tig,

        tir,

        tiv,

        tkl,

        tlh,

        tli,

        tmh,

        tog,

        ton,

        tpi,

        tsi,

        tsn,

        tso,

        tuk,

        tum,

        tup,

        tur,

        tut,

        tvl,

        twi,

        tyv,

        udm,

        uga,

        uig,

        ukr,

        umb,

        und,

        urd,

        uzb,

        vai,

        ven,

        vie,

        vol,

        vot,

        wak,

        wal,

        war,

        was,

        wel,

        wen,

        wln,

        wol,

        xal,

        xho,

        yao,

        yap,

        yid,

        yor,

        ypk,

        zap,

        zbl,

        zen,

        zgh,

        zha,

        znd,

        zul,

        zun,

        zxx,

        zza,
    }

    [GeneratedCode("xsd", "0.0.0.0")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum LayerType
    {
        PTP,

        OTP,
    }

    [GeneratedCode("xsd", "0.0.0.0")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum MediaScanElement
    {
        up,

        down,

        front,

        back,

        left,

        right,
    }

    [GeneratedCode("xsd", "0.0.0.0")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum ReleaseType
    {
        Retail,

        Bundle,

        Coverdisc,

        Subscription,

        Demo,

        OEM,

        Shareware,

        FOSS,

        Adware,

        Donationware,

        [XmlEnum("Digital download")]
        Digitaldownload,

        SaaS,
    }

    [GeneratedCode("xsd", "0.0.0.0")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum SourceFormat
    {
        [XmlEnum("ITU-A")]
        ITUA,

        [XmlEnum("ITU-B")]
        ITUB,

        [XmlEnum("ITU-C")]
        ITUC,

        [XmlEnum("ITU-D")]
        ITUD,

        [XmlEnum("ITU-E")]
        ITUE,

        [XmlEnum("ITU-F")]
        ITUF,

        [XmlEnum("ITU-G")]
        ITUG,

        [XmlEnum("ITU-H")]
        ITUH,

        [XmlEnum("ITU-I")]
        ITUI,

        [XmlEnum("ITU-J")]
        ITUJ,

        [XmlEnum("ITU-K")]
        ITUK,

        [XmlEnum("ITU-L")]
        ITUL,

        [XmlEnum("ITU-M")]
        ITUM,

        [XmlEnum("ITU-N")]
        ITUN,

        [XmlEnum("PAL-B")]
        PALB,

        [XmlEnum("SECAM-B")]
        SECAMB,

        [XmlEnum("PAL-D")]
        PALD,

        [XmlEnum("SECAM-D")]
        SECAMD,

        [XmlEnum("PAL-G")]
        PALG,

        [XmlEnum("SECAM-G")]
        SECAMG,

        [XmlEnum("PAL-H")]
        PALH,

        [XmlEnum("PAL-I")]
        PALI,

        [XmlEnum("PAL-K")]
        PALK,

        [XmlEnum("SECAM-K")]
        SECAMK,

        [XmlEnum("NTSC-M")]
        NTSCM,

        [XmlEnum("PAL-N")]
        PALN,

        [XmlEnum("PAL-M")]
        PALM,

        [XmlEnum("SECAM-M")]
        SECAMM,

        MUSE,

        PALplus,

        FM,

        AM,

        COFDM,

        [XmlEnum("CAM-D")]
        CAMD,

        DAB,

        [XmlEnum("DAB+")]
        DAB1,

        DRM,

        [XmlEnum("DRM+")]
        DRM1,

        FMeXtra,

        ATSC,

        ATSC2,

        ATSC3,

        [XmlEnum("ATSC-M/H")]
        ATSCMH,

        [XmlEnum("DVB-T")]
        DVBT,

        [XmlEnum("DVB-T2")]
        DVBT2,

        [XmlEnum("DVB-S")]
        DVBS,

        [XmlEnum("DVB-S2")]
        DVBS2,

        [XmlEnum("DVB-S2X")]
        DVBS2X,

        [XmlEnum("DVB-C")]
        DVBC,

        [XmlEnum("DVB-C2")]
        DVBC2,

        [XmlEnum("DVB-H")]
        DVBH,

        [XmlEnum("DVB-NGH")]
        DVBNGH,

        [XmlEnum("DVB-SH")]
        DVBSH,

        [XmlEnum("ISDB-T")]
        ISDBT,

        [XmlEnum("ISDB-Tb")]
        ISDBTb,

        [XmlEnum("ISDB-S")]
        ISDBS,

        [XmlEnum("ISDB-C")]
        ISDBC,

        [XmlEnum("1seg")]
        Item1seg,

        DTMB,

        CCMB,

        [XmlEnum("T-DMB")]
        TDMB,

        [XmlEnum("S-DMB")]
        SDMB,

        IPTV,

        [XmlEnum("DVB-MT")]
        DVBMT,

        [XmlEnum("DVB-MC")]
        DVBMC,

        [XmlEnum("DVB-MS")]
        DVBMS,

        ADR,

        SDR,
    }

    [GeneratedCode("xsd", "0.0.0.0")]
    [Serializable]
    [XmlType(AnonymousType = true)]
    public enum TrackType
    {
        audio,

        mode0,

        mode1,

        mode2,

        m2f1,

        m2f2,

        dvd,

        hddvd,

        bluray,

        ddcd,
    }
}
