//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
//This source code was auto-generated by MonoXSD
//

// Originally sourced from https://github.com/aaru-dps/Aaru/blob/v5.4/CICMMetadata/dotnet/cicm.cs
// The above header is from the original generated code
// Some formatting cleanup has been done to fit project standards

using System;
using System.CodeDom.Compiler;
using System.Xml.Serialization;

namespace SabreTools.Data.Models.CICM
{
    [GeneratedCode("xsd", "0.0.0.0")]
    [Serializable]
    public class EVPD
    {
        public string Image { get; set; }

        public ulong Size { get; set; }

        [XmlArrayItem("Checksum", IsNullable = false)]
        public Checksum[] Checksums { get; set; }

        [XmlAttribute]
        public byte page { get; set; }

        [XmlIgnore]
        public bool pageSpecified { get; set; }
    }
}
