//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
//This source code was auto-generated by MonoXSD
//

// Originally sourced from https://github.com/aaru-dps/Aaru/blob/v5.4/CICMMetadata/dotnet/cicm.cs
// The above header is from the original generated code
// Some formatting cleanup has been done to fit project standards

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace SabreTools.Data.Models.CICM
{
    [GeneratedCode("xsd", "0.0.0.0")]
    [Serializable]
    [DesignerCategory("code")]
    public class FileSystem
    {
        public string Type { get; set; }

        public System.DateTime CreationDate { get; set; }

        [XmlIgnore]
        public bool CreationDateSpecified { get; set; }

        public System.DateTime ModificationDate { get; set; }

        [XmlIgnore]
        public bool ModificationDateSpecified { get; set; }

        public System.DateTime BackupDate { get; set; }

        [XmlIgnore]
        public bool BackupDateSpecified { get; set; }

        public uint ClusterSize { get; set; }

        public ulong Clusters { get; set; }

        public ulong Files { get; set; }

        [XmlIgnore]
        public bool FilesSpecified { get; set; }

        public bool Bootable { get; set; }

        public string VolumeSerial { get; set; }

        public string VolumeName { get; set; }

        public ulong FreeClusters { get; set; }

        [XmlIgnore]
        public bool FreeClustersSpecified { get; set; }

        public bool Dirty { get; set; }

        public System.DateTime ExpirationDate { get; set; }

        [XmlIgnore]
        public bool ExpirationDateSpecified { get; set; }

        public System.DateTime EffectiveDate { get; set; }

        [XmlIgnore]
        public bool EffectiveDateSpecified { get; set; }

        public string SystemIdentifier { get; set; }

        public string VolumeSetIdentifier { get; set; }

        public string PublisherIdentifier { get; set; }

        public string DataPreparerIdentifier { get; set; }

        public string ApplicationIdentifier { get; set; }

        public FilesystemContents Contents { get; set; }
    }
}
