//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
//This source code was auto-generated by MonoXSD
//

// Originally sourced from https://github.com/aaru-dps/Aaru/blob/v5.4/CICMMetadata/dotnet/cicm.cs
// The above header is from the original generated code
// Some formatting cleanup has been done to fit project standards

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace SabreTools.Data.Models.CICM
{
    [GeneratedCode("xsd", "0.0.0.0")]
    [Serializable]
    [DesignerCategory("code")]
    public class LinearMedia
    {
        public Image Image { get; set; }

        public ulong Size { get; set; }

        [XmlArrayItem("Checksum", IsNullable = false)]
        public Checksum[] ImageChecksums { get; set; }

        [XmlArrayItem("Checksum", IsNullable = false)]
        public Checksum[] Checksums { get; set; }

        public string PartNumber { get; set; }

        public string SerialNumber { get; set; }

        public string Title { get; set; }

        public uint Sequence { get; set; }

        [XmlIgnore]
        public bool SequenceSpecified { get; set; }

        public uint ImageInterleave { get; set; }

        [XmlIgnore]
        public bool ImageInterleaveSpecified { get; set; }

        public uint Interleave { get; set; }

        [XmlIgnore]
        public bool InterleaveSpecified { get; set; }

        public string Manufacturer { get; set; }

        public string Model { get; set; }

        public string Package { get; set; }

        public string Interface { get; set; }

        public Dimensions Dimensions { get; set; }

        public Scans Scans { get; set; }

        [XmlArrayItem("DumpHardware", IsNullable = false)]
        public DumpHardware[] DumpHardwareArray { get; set; }

        public PCMCIA PCMCIA { get; set; }

        public string CopyProtection { get; set; }
    }
}
