//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
//This source code was auto-generated by MonoXSD
//

// Originally sourced from https://github.com/aaru-dps/Aaru/blob/v5.4/CICMMetadata/dotnet/cicm.cs
// The above header is from the original generated code
// Some formatting cleanup has been done to fit project standards

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace SabreTools.Data.Models.CICM
{
    [GeneratedCode("xsd", "0.0.0.0")]
    [Serializable]
    [DesignerCategory("code")]
    public class Magazine
    {
        [XmlArrayItem("Barcode", IsNullable = false)]
        public Barcode[] Barcodes { get; set; }

        public Cover Cover { get; set; }

        public string Name { get; set; }

        public string Editorial { get; set; }

        [XmlElement(DataType = "date")]
        public System.DateTime PublicationDate { get; set; }

        [XmlIgnore]
        public bool PublicationDateSpecified { get; set; }

        public uint Number { get; set; }

        [XmlIgnore]
        public bool NumberSpecified { get; set; }

        [XmlArrayItem("Language", IsNullable = false)]
        public Language[] Language { get; set; }

        public uint Pages { get; set; }

        [XmlIgnore]
        public bool PagesSpecified { get; set; }

        public string PageSize { get; set; }

        public Scan Scan { get; set; }
    }
}
