//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
//This source code was auto-generated by MonoXSD
//

// Originally sourced from https://github.com/aaru-dps/Aaru/blob/v5.4/CICMMetadata/dotnet/cicm.cs
// The above header is from the original generated code
// Some formatting cleanup has been done to fit project standards

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace SabreTools.Data.Models.CICM
{
    [GeneratedCode("xsd", "0.0.0.0")]
    [Serializable]
    [DesignerCategory("code")]
    public class Track
    {
        public Image Image { get; set; }

        public ulong Size { get; set; }

        public TrackSequence Sequence { get; set; }

        public string StartMSF { get; set; }

        public string EndMSF { get; set; }

        public ulong StartSector { get; set; }

        public ulong EndSector { get; set; }

        [XmlArrayItem("Index", IsNullable = false)]
        public TrackIndex[] Indexes { get; set; }

        public TrackFlags Flags { get; set; }

        public string ISRC { get; set; }

        [XmlElement("TrackType")]
        public TrackType TrackType { get; set; }

        public uint BytesPerSector { get; set; }

        public string AccoustID { get; set; }

        [XmlArrayItem("Checksum", IsNullable = false)]
        public Checksum[] Checksums { get; set; }

        public SubChannel SubChannel { get; set; }

        [XmlArrayItem("Partition", IsNullable = false)]
        public Partition[] FileSystemInformation { get; set; }
    }
}
